services:
  chefknifestudios.expensetracker.webapi:
    build:
      context: .
      dockerfile: ./src/ChefKnifeStudios.ExpenseTracker.WebAPI/Dockerfile
    image: ${CONTAINER_REGISTRY:-localhost:5000}/chefknifestudios.expensetracker.webapi:${CONTAINER_TAG:-latest}

  chefknifestudios.expensetracker.data:
    build:
      context: .
      dockerfile: ./src/ChefKnifeStudios.ExpenseTracker.Data/Dockerfile
    image: ${CONTAINER_REGISTRY:-localhost:5000}/chefknifestudios.expensetracker.data:${CONTAINER_TAG:-latest}

  chefknifestudios.expensetracker.recurringexpensefunctionapp:
    build:
      context: .
      dockerfile: ./src/ChefKnifeStudios.ExpenseTracker.RecurringExpenseFunctionApp/Dockerfile
    image: ${CONTAINER_REGISTRY:-localhost:5000}/chefknifestudios.expensetracker.recurringexpensefunctionapp:${CONTAINER_TAG:-latest}