# youtube series: https://www.youtube.com/watch?v=eLY9EDzyvoQ&list=PL0jJqThQHximeZ2a0HKaRx44s8UDIRkuY&index=3

name: $(SourceBranchName)-expense-tracker-maui-$(Date:yyyyMMdd).$(Rev:r)-$(app_version_major).$(app_version_minor).$(app_version_patch)+$(app_version_code)

trigger:
  branches:
    include:
    - main
    - release/*
    - maui-deploy
pr: none

variables:
  - group: 'Prod-ExpenseTracker'
  - group: 'Versions'
  - name: 'AppBuildVersion'
    value: $(app_version_major).$(app_version_minor).$(app_version_patch)

stages:
  - stage: ios_stage
    displayName: iOS Stage
    pool:
      name: Azure Pipelines
      vmImage: macOS-15
    jobs:
      - job: ios_job
        displayName: iOS job
        steps:
          - template: maui-setup-template.yml
          
          - task: InstallAppleProvisioningProfile@1
            inputs:
              provisioningProfileLocation: 'secureFiles'
              provProfileSecureFile: Expense_Tracker_Profile.mobileprovision
          
          - task: InstallAppleCertificate@2
            inputs:
              certSecureFile: Distribution.p12
              keychain: 'temp' 
              certPwd: $(ios_distribution_password)

          - task: Bash@3
            displayName: Build iOS MAUI app
            inputs:
              targetType: 'inline'
              script: |
                dotnet publish src/ChefKnifeStudios.ExpenseTracker.MobileApp/ChefKnifeStudios.ExpenseTracker.MobileApp.csproj -f net9.0-ios -c Release --output '$(Build.ArtifactStagingDirectory)/iOS' -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="$(codesign_key)" -p:CodesignProvision="$(codesign_provision)" -p:ApplicationDisplayVersion=$(app_build_version) -p:ApplicationVersion=$(app_version_code)

          - task: PublishBuildArtifacts@1
            displayName: 'Publish iOS app to artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/iOS'
              ArtifactName: 'iOS'