
name: $(SourceBranchName)-expense-tracker-$(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
    - main
    - release/*
    - deploy-1
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  azure-subscription-service-connection: ChefKnifeStudiosSC
  container-registry: chefknife.azurecr.io
  container-tag: $(Build.BuildNumber)
  container-registry-service-connection: AzureContainerRegistrySC
  api-container-name: chefknifestudios.expensetracker.webapi
  api-container: $(container-registry)/$(api-container-name):$(container-tag)
  migration-container-name: chefknifestudios.expensetracker.data
  migration-container: $(container-registry)/$(migration-container-name):$(container-tag)
  function-container-name: chefknifestudios.expensetracker.recurringexpensefunctionapp
  function-container: $(container-registry)/$(function-container-name):$(container-tag)

stages:
- stage: BuildAndPublish
  displayName: Build and Publish ChefKnifeStudios.ExpenseTracker.WebAPI
  jobs:
  - job: BuildAndPublish
    displayName: Build and Publish ChefKnifeStudios.ExpenseTracker.WebAPI

    variables:
      buildConfiguration: 'Release'

    steps:
    - checkout: self
      persistCredentials: true # Required for git tagging 

    - task: Docker@2
      inputs:
        containerRegistry: '$(container-registry-service-connection)'
        command: 'login'

    - script: |
        docker compose build
      displayName: Docker compose build
      env:
        CONTAINER_REGISTRY: $(container-registry)
        CONTAINER_TAG: $(container-tag)

    - script: |
        docker push $(api-container)
        docker push $(migration-container)
      displayName: Docker push images

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.x.x'

    - task: DotNetCoreCLI@2
      displayName: 'Build Function App'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/ChefKnifeStudios.ExpenseTracker.RecurringExpenseFunctionApp.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/publish'
        zipAfterPublish: true

- stage: DeployProd
  displayName: Deploy Production
  jobs: 
  - deployment: DeployProd
    displayName: Deploy ChefKnifeStudios.ExpenseTracker.WebAPI to Prod
    environment: 'Prod'
    variables:
    - group: 'Prod-ExpenseTracker'
    strategy:
      runOnce:   
        deploy:
          steps:
          - checkout: self
            persistCredentials: true # Required for git tagging  

          - task: Docker@2
            inputs:
              containerRegistry: '$(container-registry-service-connection)'
              command: 'login'

          # DB Migration
          - script: |
              docker run --rm -e CONNECTIONSTRINGS__EXPENSETRACKERDB $(migration-container)
            displayName: 'Run DB Migrations'
            env:
              CONNECTIONSTRINGS__EXPENSETRACKERDB: $(ConnectionStrings-ExpenseTrackerDB)

          # Deploy API Container App
          - task: AzureContainerApps@1
            displayName: "Deploy API Container App"
            inputs:
              azureSubscription: '$(azure-subscription-service-connection)'
              imageToDeploy: '$(api-container)'
              containerAppName: expense-tracker-api
              resourceGroup: 'expense-tracker'
              containerAppEnvironment: 'expense-tracker-api-env'

          # Deploy ChefKnifeStudios.ExpenseTracker.RecurringExpenseFunctionApp
          - task: AzureFunctionApp@1
            displayName: 'Deploy Function App via ZIP'
            inputs:
              azureSubscription: '$(azure-subscription-service-connection)'
              appType: 'functionApp'
              appName: 'recurring-expense-fn'
              package: '$(Build.ArtifactStagingDirectory)/publish/**/*.zip'
